server:
  port: 3001
spring:
  application:
    name: user
eureka:
  client:
    serviceUrl:
      defaultZone: http://admin:pwd@localhost:8761/eureka/
management:
  endpoints:
    web:
      exposure:
        include: "*"