spring:
  application:
    name: user-consumer
  boot:
    admin:
      client:
        url: localhost:5000
feign:
  hystrix:
    enabled: true
eureka:
  client:
    serviceUrl:
      defaultZone: http://admin:pwd@localhost:8761/eureka/
server:
  port: 4001
logging:
  file: user-consumer.log
management:
  endpoints:
    web:
      exposure:
        include: "*"
mcloud:
  redis:
    ssl: false
    timeout: 0
    jedis:
      pool:
        maxIdle: 8
        minIdle: 0
        maxActive: 8
        maxWait: 1
    cluster:
      nodes:
        - 192.168.0.244:7001
        - 192.168.0.244:7002
        - 192.168.0.244:7003
        - 192.168.0.244:7004
        - 192.168.0.244:7005
        - 192.168.0.244:7006
      maxRedirects: 6